// <auto-generated />
using System;
using EFCoreModelingDrills.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace task_01_drills.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260914142131_AddSeedData")]
    partial class AddSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EFCoreModelingDrills.Entities.Enrollment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("FinalGrade")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("TrackId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("TrackId");

                    b.ToTable("Enrollments");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            EnrollmentDate = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Active",
                            StudentId = 101,
                            TrackId = 101
                        },
                        new
                        {
                            Id = 102,
                            EnrollmentDate = new DateTime(2026, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinalGrade = 92.50m,
                            Status = "Completed",
                            StudentId = 101,
                            TrackId = 102
                        },
                        new
                        {
                            Id = 103,
                            EnrollmentDate = new DateTime(2026, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Active",
                            StudentId = 102,
                            TrackId = 101
                        },
                        new
                        {
                            Id = 104,
                            EnrollmentDate = new DateTime(2026, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinalGrade = 88.00m,
                            Status = "Completed",
                            StudentId = 103,
                            TrackId = 103
                        },
                        new
                        {
                            Id = 105,
                            EnrollmentDate = new DateTime(2026, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Active",
                            StudentId = 104,
                            TrackId = 102
                        });
                });

            modelBuilder.Entity("EFCoreModelingDrills.Entities.Instructor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Instructors");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            FullName = "Ahmed Samir"
                        },
                        new
                        {
                            Id = 102,
                            FullName = "Nour Khaled"
                        });
                });

            modelBuilder.Entity("EFCoreModelingDrills.Entities.PaymentSummary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EnrollmentId")
                        .HasColumnType("int");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("RemainingAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalRequired")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("EnrollmentId")
                        .IsUnique();

                    b.ToTable("PaymentSummaries");
                });

            modelBuilder.Entity("EFCoreModelingDrills.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            CreatedAt = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ahmed.ali@techmaster.com",
                            FullName = "Ahmed Ali",
                            IsActive = true
                        },
                        new
                        {
                            Id = 102,
                            CreatedAt = new DateTime(2026, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mona.hassan@techmaster.com",
                            FullName = "Mona Hassan",
                            IsActive = true
                        },
                        new
                        {
                            Id = 103,
                            CreatedAt = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "omar.mohamed@techmaster.com",
                            FullName = "Omar Mohamed",
                            IsActive = true
                        },
                        new
                        {
                            Id = 104,
                            CreatedAt = new DateTime(2026, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sara.mahmoud@techmaster.com",
                            FullName = "Sara Mahmoud",
                            IsActive = true
                        },
                        new
                        {
                            Id = 105,
                            CreatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "youssef.ibrahim@techmaster.com",
                            FullName = "Youssef Ibrahim",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("EFCoreModelingDrills.Entities.StudentProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentId")
                        .IsUnique();

                    b.ToTable("StudentProfiles");
                });

            modelBuilder.Entity("EFCoreModelingDrills.Entities.Track", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("InstructorId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("InstructorId");

                    b.ToTable("Tracks");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            InstructorId = 101,
                            Name = "ASP.NET Core Backend"
                        },
                        new
                        {
                            Id = 102,
                            InstructorId = 101,
                            Name = "Database & EF Core"
                        },
                        new
                        {
                            Id = 103,
                            InstructorId = 102,
                            Name = "Web API Development"
                        });
                });

            modelBuilder.Entity("EFCoreModelingDrills.Entities.Enrollment", b =>
                {
                    b.HasOne("EFCoreModelingDrills.Entities.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EFCoreModelingDrills.Entities.Track", "Track")
                        .WithMany("Enrollments")
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("EFCoreModelingDrills.Entities.PaymentSummary", b =>
                {
                    b.HasOne("EFCoreModelingDrills.Entities.Enrollment", "Enrollment")
                        .WithOne("PaymentSummary")
                        .HasForeignKey("EFCoreModelingDrills.Entities.PaymentSummary", "EnrollmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enrollment");
                });

            modelBuilder.Entity("EFCoreModelingDrills.Entities.StudentProfile", b =>
                {
                    b.HasOne("EFCoreModelingDrills.Entities.Student", "Student")
                        .WithOne("Profile")
                        .HasForeignKey("EFCoreModelingDrills.Entities.StudentProfile", "StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("EFCoreModelingDrills.Entities.Track", b =>
                {
                    b.HasOne("EFCoreModelingDrills.Entities.Instructor", "Instructor")
                        .WithMany("Tracks")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("EFCoreModelingDrills.Entities.Enrollment", b =>
                {
                    b.Navigation("PaymentSummary");
                });

            modelBuilder.Entity("EFCoreModelingDrills.Entities.Instructor", b =>
                {
                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("EFCoreModelingDrills.Entities.Student", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("EFCoreModelingDrills.Entities.Track", b =>
                {
                    b.Navigation("Enrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
