<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>debug_refactor_pack</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="original-bad-code\**" />
    <EmbeddedResource Remove="original-bad-code\**" />
    <None Remove="original-bad-code\**" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Screenshots\" />
    <Folder Include="refactored-code\Services\" />
  </ItemGroup>

</Project>
